version: '3.4'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - db-data:/data
    networks:
      backend:
        aliases:
          - redis
    container_name: redis

  monitor:
    depends_on:
      - redis
    build: .
    restart: always
    command: bash -c 'bundle config without "" && bundle install && bundle exec foreman start'
    volumes:
      - .:/opt/slug
    environment:
      RELEASE: development
      SLUG_ENV: development
    ports:
      - 7071:7071
      - 10002:10002
    networks:
      backend:
        aliases:
          - monitor
    container_name: monitor

volumes:
  db-data:

networks:
  backend: