version: '3.4'

services:
  redis:
    image: quay.io/3scale/redis
    restart: always
    volumes:
      - db-data:/data
    networks:
      backend:
        aliases:
          - redis
    container_name: apitools-redis

  apitools:
    depends_on:
      - redis
    build: .
    restart: always
    command: bash -c 'bundle config without "" && bundle install && bundle exec foreman start'
    volumes:
      - .:/opt/slug
    environment:
      RELEASE: development
      SLUG_ENV: development
    ports:
      - 7071:7071
      - 10002:10002
    networks:
      backend:
        aliases:
          - apitools
    container_name: apitools

volumes:
  db-data:

networks:
  backend: