version: '3.6'

services:
  redis:
    image: quay.io/3scale/redis
    restart: always
    volumes:
      - db-data:/data
    networks:
      backend:
        aliases:
          - redis
    container_name: apitools-redis

  apitools:
    depends_on:
      - redis
    image: quay.io/3scale/apitools
    restart: always
    volumes:
      - .:/var/www/brainslug
    ports:
      - 7071:7071
      - 10002:10002
    networks:
      backend:
        aliases:
          - apitools
    container_name: apitools

volumes:
  db-data:

networks:
  backend: